[package]
name = "tetris_html"
version = "0.1.0"
edition = "2024"

[dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }
leptos = { version = "0.7.8", features = ["csr"] }
rand = "0.9.0"
reactive_stores = "0.1.8"
web-sys = { version = "0.3.77", features = ["Window", "Document"] }
